### ISSUE TITLE
Project 2 Pitch README

### ISSUE THREAD

**Issue by kerby51** [kerby51/Bill-Organizer#1]
# Bill-Organizer
## Project MVP

Monthly Bill Organizer
  -a page where a user can go and manually enter/organize their bills each month
## Technologies

ReactJS
Firebase
HTML
CSS
## Next Steps

-build the environment
-create firebase database
-set up user auth (either first or last)
-work on homepage component
-create active links for each month of the year in nav section
-work on a single month component with a route to that month
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-list/form of bill description and amount
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-figure out how to have an input formatted to a dollar amount (??)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-total the amounts (??)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-have ability to delete/add to the form
## Bonuses

-Biggest challenge - totaling the inputs
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-ensuring the total changes with every add/delete?
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-total being stored in firebase/remaining same when page refreshed

**Comment by amadden80** [comment]
Let's Chat
